//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Birimler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Birimler()
        {
            this.Birimler1 = new HashSet<Birimler>();
            this.KullaniciBirimleris = new HashSet<KullaniciBirimleri>();
            this.KullaniciBirimleriRapors = new HashSet<KullaniciBirimleriRapor>();
            this.Kullanicilars = new HashSet<Kullanicilar>();
            this.VASurecleriBirims = new HashSet<VASurecleriBirim>();
        }
    
        public int BirimID { get; set; }
        public Nullable<int> UstBirimID { get; set; }
        public string BirimAdi { get; set; }
        public bool IsVeriGirisiYapilabilir { get; set; }
        public Nullable<int> VeriGirisTipID { get; set; }
        public string YeniUniteKodu { get; set; }
        public string EskiUniteKodu { get; set; }
        public string IsyeriSiraNumarasi { get; set; }
        public string IlKodu { get; set; }
        public string AltIsverenNumarasi { get; set; }
        public bool IsAyAsiriHesaplama { get; set; }
        public Nullable<int> AyBaslangicGun { get; set; }
        public Nullable<int> GelecekAyBitisGun { get; set; }
        public bool IsAktif { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Birimler> Birimler1 { get; set; }
        public virtual Birimler Birimler2 { get; set; }
        public virtual VeriGirisTipleri VeriGirisTipleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciBirimleri> KullaniciBirimleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciBirimleriRapor> KullaniciBirimleriRapors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kullanicilar> Kullanicilars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VASurecleriBirim> VASurecleriBirims { get; set; }
    }
}
