//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanicilar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanicilar()
        {
            this.Ayarlars = new HashSet<Ayarlar>();
            this.BelgeMahiyetTipleris = new HashSet<BelgeMahiyetTipleri>();
            this.BelgeTurleris = new HashSet<BelgeTurleri>();
            this.Birimlers = new HashSet<Birimler>();
            this.Duyurulars = new HashSet<Duyurular>();
            this.EksikGunNedenleris = new HashSet<EksikGunNedenleri>();
            this.GonderilenMailKullanicilars = new HashSet<GonderilenMailKullanicilar>();
            this.GonderilenMaillers = new HashSet<GonderilenMailler>();
            this.IstenCikisNedenleris = new HashSet<IstenCikisNedenleri>();
            this.KullaniciBirimleris = new HashSet<KullaniciBirimleri>();
            this.KullaniciBirimleriRapors = new HashSet<KullaniciBirimleriRapor>();
            this.Mesajlars = new HashSet<Mesajlar>();
            this.MesajKategorileris = new HashSet<MesajKategorileri>();
            this.MeslekTurleris = new HashSet<MeslekTurleri>();
            this.SistemBilgilendirmes = new HashSet<SistemBilgilendirme>();
            this.Rollers = new HashSet<Roller>();
        }
    
        public int KullaniciID { get; set; }
        public int YetkiGrupID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public int BirimID { get; set; }
        public int UnvanID { get; set; }
        public string Tel { get; set; }
        public string EMail { get; set; }
        public string ResimAdi { get; set; }
        public string KullaniciAdi { get; set; }
        public string Sifre { get; set; }
        public bool SifresiniDegistirsin { get; set; }
        public bool IsActiveDirectoryUser { get; set; }
        public bool IsAdmin { get; set; }
        public string Aciklama { get; set; }
        public string ParolaSifirlamaKodu { get; set; }
        public Nullable<System.DateTime> ParolaSifirlamGecerlilikTarihi { get; set; }
        public bool FixedHeader { get; set; }
        public bool FixedSidebar { get; set; }
        public bool ScrollSidebar { get; set; }
        public bool RightSidebar { get; set; }
        public bool CustomNavigation { get; set; }
        public bool ToggledNavigation { get; set; }
        public bool BoxedOrFullWidth { get; set; }
        public string ThemeName { get; set; }
        public string BackgroundImage { get; set; }
        public bool IsAktif { get; set; }
        public Nullable<System.DateTime> OlusturmaTarihi { get; set; }
        public Nullable<System.DateTime> LastLogonDate { get; set; }
        public string LastLogonIP { get; set; }
        public Nullable<int> IslemYapanID { get; set; }
        public Nullable<System.DateTime> IslemTarihi { get; set; }
        public string IslemYapanIP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ayarlar> Ayarlars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BelgeMahiyetTipleri> BelgeMahiyetTipleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BelgeTurleri> BelgeTurleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Birimler> Birimlers { get; set; }
        public virtual Birimler Birimler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Duyurular> Duyurulars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EksikGunNedenleri> EksikGunNedenleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GonderilenMailKullanicilar> GonderilenMailKullanicilars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GonderilenMailler> GonderilenMaillers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IstenCikisNedenleri> IstenCikisNedenleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciBirimleri> KullaniciBirimleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciBirimleriRapor> KullaniciBirimleriRapors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mesajlar> Mesajlars { get; set; }
        public virtual Unvanlar Unvanlar { get; set; }
        public virtual YetkiGruplari YetkiGruplari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MesajKategorileri> MesajKategorileris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeslekTurleri> MeslekTurleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SistemBilgilendirme> SistemBilgilendirmes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Roller> Rollers { get; set; }
    }
}
