//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MusskDBEntities : DbContext
    {
        public MusskDBEntities()
            : base("name=MusskDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ayarlar> Ayarlars { get; set; }
        public virtual DbSet<AyDurumlari> AyDurumlaris { get; set; }
        public virtual DbSet<Aylar> Aylars { get; set; }
        public virtual DbSet<BelgeMahiyetTipleri> BelgeMahiyetTipleris { get; set; }
        public virtual DbSet<BelgeTurleri> BelgeTurleris { get; set; }
        public virtual DbSet<Birimler> Birimlers { get; set; }
        public virtual DbSet<DuyuruEkleri> DuyuruEkleris { get; set; }
        public virtual DbSet<Duyurular> Duyurulars { get; set; }
        public virtual DbSet<EksikGunNedenleri> EksikGunNedenleris { get; set; }
        public virtual DbSet<GonderilenMailEkleri> GonderilenMailEkleris { get; set; }
        public virtual DbSet<GonderilenMailKullanicilar> GonderilenMailKullanicilars { get; set; }
        public virtual DbSet<GonderilenMailler> GonderilenMaillers { get; set; }
        public virtual DbSet<IstenCikisNedenleri> IstenCikisNedenleris { get; set; }
        public virtual DbSet<KullaniciBirimleri> KullaniciBirimleris { get; set; }
        public virtual DbSet<KullaniciBirimleriRapor> KullaniciBirimleriRapors { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilars { get; set; }
        public virtual DbSet<KullaniciYevmiyeHesapKodTurYetkileri> KullaniciYevmiyeHesapKodTurYetkileris { get; set; }
        public virtual DbSet<MailSablonlari> MailSablonlaris { get; set; }
        public virtual DbSet<MailSablonlariEkleri> MailSablonlariEkleris { get; set; }
        public virtual DbSet<MailSablonTipleri> MailSablonTipleris { get; set; }
        public virtual DbSet<Menuler> Menulers { get; set; }
        public virtual DbSet<MesajEkleri> MesajEkleris { get; set; }
        public virtual DbSet<MesajKategorileri> MesajKategorileris { get; set; }
        public virtual DbSet<Mesajlar> Mesajlars { get; set; }
        public virtual DbSet<MeslekTurleri> MeslekTurleris { get; set; }
        public virtual DbSet<Roller> Rollers { get; set; }
        public virtual DbSet<SistemBilgilendirme> SistemBilgilendirmes { get; set; }
        public virtual DbSet<Unvanlar> Unvanlars { get; set; }
        public virtual DbSet<VASurecleri> VASurecleris { get; set; }
        public virtual DbSet<VASurecleriAylar> VASurecleriAylars { get; set; }
        public virtual DbSet<VASurecleriBirim> VASurecleriBirims { get; set; }
        public virtual DbSet<VASurecleriBirimVerileri> VASurecleriBirimVerileris { get; set; }
        public virtual DbSet<VASurecleriBirimVerileriAylikToplam> VASurecleriBirimVerileriAylikToplams { get; set; }
        public virtual DbSet<VeriGirisTipleri> VeriGirisTipleris { get; set; }
        public virtual DbSet<YetkiGruplari> YetkiGruplaris { get; set; }
        public virtual DbSet<YetkiGrupRolleri> YetkiGrupRolleris { get; set; }
        public virtual DbSet<Yevmiyeler> Yevmiyelers { get; set; }
        public virtual DbSet<Yevmiyeler1003AGelirKayit> Yevmiyeler1003AGelirKayit { get; set; }
        public virtual DbSet<Yevmiyeler1003BAyristirmalari> Yevmiyeler1003BAyristirmalari { get; set; }
        public virtual DbSet<YevmiyelerBelgeKodlari> YevmiyelerBelgeKodlaris { get; set; }
        public virtual DbSet<YevmiyelerBesBankaHesapNumaralari> YevmiyelerBesBankaHesapNumaralaris { get; set; }
        public virtual DbSet<YevmiyelerHarcamaBirimleri> YevmiyelerHarcamaBirimleris { get; set; }
        public virtual DbSet<YevmiyelerHarcamaBirimleriTutarKayit> YevmiyelerHarcamaBirimleriTutarKayits { get; set; }
        public virtual DbSet<YevmiyelerHesapKodlari> YevmiyelerHesapKodlaris { get; set; }
        public virtual DbSet<YevmiyelerHesapKodTurleri> YevmiyelerHesapKodTurleris { get; set; }
        public virtual DbSet<YevmiyelerKdvKodlari> YevmiyelerKdvKodlaris { get; set; }
        public virtual DbSet<YevmiyelerKdvTevkifatKayitlari> YevmiyelerKdvTevkifatKayitlaris { get; set; }
        public virtual DbSet<YevmiyelerProjeBankaHesapNumaralari> YevmiyelerProjeBankaHesapNumaralaris { get; set; }
        public virtual DbSet<YevmiyelerSendikaBilgileri> YevmiyelerSendikaBilgileris { get; set; }
        public virtual DbSet<YevmiyelerTasinirKontrolTifKaydi> YevmiyelerTasinirKontrolTifKaydis { get; set; }
        public virtual DbSet<YevmiyelerVergiKimlikNumaralari> YevmiyelerVergiKimlikNumaralaris { get; set; }
        public virtual DbSet<KullanicilarLog> KullanicilarLogs { get; set; }
        public virtual DbSet<Vw_BirimlerTree> Vw_BirimlerTree { get; set; }
    
        public virtual ObjectResult<sp_BirimAgaci_Result> sp_BirimAgaci()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BirimAgaci_Result>("sp_BirimAgaci");
        }
    
        public virtual ObjectResult<sp_BirimAgaciGetBr_Result> sp_BirimAgaciGetBr(Nullable<int> birimID)
        {
            var birimIDParameter = birimID.HasValue ?
                new ObjectParameter("BirimID", birimID) :
                new ObjectParameter("BirimID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BirimAgaciGetBr_Result>("sp_BirimAgaciGetBr", birimIDParameter);
        }
    }
}
