//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class VASurecleriAylar
    {
        public int VASurecleriAyID { get; set; }
        public int VASurecID { get; set; }
        public int AyID { get; set; }
        public int AyDurumID { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual AyDurumlari AyDurumlari { get; set; }
        public virtual Aylar Aylar { get; set; }
        public virtual VASurecleri VASurecleri { get; set; }
    }
}
