//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class VASurecleriBirim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VASurecleriBirim()
        {
            this.VASurecleriBirimVerileris = new HashSet<VASurecleriBirimVerileri>();
            this.VASurecleriBirimVerileriAylikToplams = new HashSet<VASurecleriBirimVerileriAylikToplam>();
        }
    
        public int VASurecleriBirimID { get; set; }
        public int VASurecID { get; set; }
        public int BirimID { get; set; }
        public Nullable<int> UstBirimID { get; set; }
        public bool IsVeriGirisiYapilabilir { get; set; }
        public Nullable<int> VeriGirisTipID { get; set; }
        public string YeniUniteKodu { get; set; }
        public string EskiUniteKodu { get; set; }
        public string IsyeriSiraNumarasi { get; set; }
        public string IlKodu { get; set; }
        public string AltIsverenNumarasi { get; set; }
        public bool IsAyAsiriHesaplama { get; set; }
        public Nullable<int> AyBaslangicGun { get; set; }
        public Nullable<int> GelecekAyBitisGun { get; set; }
        public bool IsAktif { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual Birimler Birimler { get; set; }
        public virtual VASurecleri VASurecleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VASurecleriBirimVerileri> VASurecleriBirimVerileris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VASurecleriBirimVerileriAylikToplam> VASurecleriBirimVerileriAylikToplams { get; set; }
    }
}
