//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class VASurecleriBirimVerileri
    {
        public int VASurecleriBirimVeriID { get; set; }
        public int VASurecleriBirimID { get; set; }
        public int AyID { get; set; }
        public string HizmetDonemYil { get; set; }
        public string HizmetDonemAy { get; set; }
        public int BelgeMahiyetTipID { get; set; }
        public string BelgeMahiyetTipKodu { get; set; }
        public int BelgeTurID { get; set; }
        public string BelgeTurKodu { get; set; }
        public decimal PrimYuzdesi { get; set; }
        public string DEsasKanunNo { get; set; }
        public string YeniUniteKodu { get; set; }
        public string EskiUniteKodu { get; set; }
        public string IsyeriSiraNumarasi { get; set; }
        public string IlKodu { get; set; }
        public string AltIsverenNumarasi { get; set; }
        public int VeriGirisTipID { get; set; }
        public string SSKSicilNo { get; set; }
        public string TcKimlikNo { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public int PrimOdemeGun { get; set; }
        public Nullable<int> UzaktanCalismaGun { get; set; }
        public decimal HakEdilenUcret { get; set; }
        public decimal PrimIkramiyeIstihkak { get; set; }
        public Nullable<int> IseGirisGun { get; set; }
        public string IseGirisGunStr { get; set; }
        public Nullable<int> IseGirisAy { get; set; }
        public string IseGirisAyStr { get; set; }
        public Nullable<int> IstenCikisGun { get; set; }
        public string IstenCikisGunStr { get; set; }
        public Nullable<int> IstenCikisAy { get; set; }
        public string IstenCikisAyStr { get; set; }
        public Nullable<int> IstenCikisNedenID { get; set; }
        public Nullable<int> IstenCikisNedenKodu { get; set; }
        public Nullable<int> EksikGunSayisi { get; set; }
        public Nullable<int> EksikGunNedenID { get; set; }
        public Nullable<int> EksikGunNedenKodu { get; set; }
        public int MeslekTurID { get; set; }
        public string MeslekTurKodu { get; set; }
        public Nullable<int> IstirahatSurecindeCalismamistir { get; set; }
        public string TahakkukNedeni { get; set; }
        public int GvDenMuafmi { get; set; }
        public Nullable<decimal> AsgariGecimIndirimi { get; set; }
        public Nullable<decimal> GvMatrahi { get; set; }
        public Nullable<int> GvEngellilikOrani { get; set; }
        public Nullable<decimal> HesaplananGv { get; set; }
        public Nullable<decimal> AsgariGecimIstisnaGvTutar { get; set; }
        public Nullable<decimal> GvKesinti { get; set; }
        public Nullable<decimal> AsgariGecimIstisnaDvTutar { get; set; }
        public Nullable<decimal> DvKesintisi { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual Aylar Aylar { get; set; }
        public virtual BelgeMahiyetTipleri BelgeMahiyetTipleri { get; set; }
        public virtual BelgeTurleri BelgeTurleri { get; set; }
        public virtual EksikGunNedenleri EksikGunNedenleri { get; set; }
        public virtual IstenCikisNedenleri IstenCikisNedenleri { get; set; }
        public virtual VASurecleriBirim VASurecleriBirim { get; set; }
        public virtual VeriGirisTipleri VeriGirisTipleri { get; set; }
    }
}
