//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class VASurecleriBirimVerileriAylikToplam
    {
        public int VASurecleriBirimVerileriAylikToplamID { get; set; }
        public int VASurecleriBirimID { get; set; }
        public int AyID { get; set; }
        public decimal AsgariGecimIndirimiToplam { get; set; }
        public decimal GvMatrahiToplam { get; set; }
        public decimal GvKesintiToplam { get; set; }
        public decimal PrimTutarToplam { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual Aylar Aylar { get; set; }
        public virtual VASurecleriBirim VASurecleriBirim { get; set; }
    }
}
