//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class VeriGirisTipleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VeriGirisTipleri()
        {
            this.Birimlers = new HashSet<Birimler>();
            this.VASurecleriBirimVerileris = new HashSet<VASurecleriBirimVerileri>();
        }
    
        public int VeriGirisTipID { get; set; }
        public string VeriGirisTipAdi { get; set; }
        public string Aciklama { get; set; }
        public bool IsAktif { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Birimler> Birimlers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VASurecleriBirimVerileri> VASurecleriBirimVerileris { get; set; }
    }
}
