//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_BirimlerTree
    {
        public string BirimTreeAdi { get; set; }
        public int BirimID { get; set; }
        public Nullable<int> UstBirimID { get; set; }
        public string BirimAdi { get; set; }
        public bool IsVeriGirisiYapilabilir { get; set; }
        public Nullable<int> VeriGirisTipID { get; set; }
        public string VeriGirisTipAdi { get; set; }
        public string YeniUniteKodu { get; set; }
        public string EskiUniteKodu { get; set; }
        public string IsyeriSiraNumarasi { get; set; }
        public string IlKodu { get; set; }
        public string AltIsverenNumarasi { get; set; }
        public bool IsAyAsiriHesaplama { get; set; }
        public Nullable<int> AyBaslangicGun { get; set; }
        public Nullable<int> GelecekAyBitisGun { get; set; }
        public bool IsAktif { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    }
}
