//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Yevmiyeler
    {
        public int YevmiyeID { get; set; }
        public Nullable<int> Yil { get; set; }
        public System.DateTime YevmiyeTarih { get; set; }
        public int YevmiyeNo { get; set; }
        public int YevmiyeHarcamaBirimID { get; set; }
        public string BirimAdi { get; set; }
        public string HarcamaBirimAdi { get; set; }
        public string VergiKimlikNo { get; set; }
        public string HarcamaBirimKod { get; set; }
        public string HesapKod { get; set; }
        public string HesapAdi { get; set; }
        public decimal Borc { get; set; }
        public decimal Alacak { get; set; }
        public string Aciklama { get; set; }
        public string BankaHesapNumarasi { get; set; }
        public Nullable<int> Y1003AHesapKodID { get; set; }
        public string Y1003AVergiKodu { get; set; }
        public bool Y1003AIsHesaplamayaGirecek { get; set; }
        public string Y1003AVergiKimlikNo { get; set; }
        public string Y1003AAdSoyad { get; set; }
        public string Y1003AAdres { get; set; }
        public Nullable<decimal> Y1003AMatrah { get; set; }
        public string Y1003ABelgeninMahiyeti { get; set; }
        public Nullable<System.DateTime> Y1003AFaturaTarihi { get; set; }
        public string Y1003AFaturaNo { get; set; }
        public Nullable<int> YevmiyeSendikaBilgiID { get; set; }
        public Nullable<int> BESYevmiyeHesapKodID { get; set; }
        public Nullable<bool> BESIsYevmiyeDokumuAyri { get; set; }
        public Nullable<bool> BESIsYevmiyeOdendi { get; set; }
        public Nullable<int> ProjeBankaHesapNoID { get; set; }
        public decimal Expr1 { get; set; }
        public Nullable<int> YevmiyeHesapKodTurID { get; set; }
        public Nullable<int> EKYevmiyeHarcamaBirimID { get; set; }
        public int Expr2 { get; set; }
        public Nullable<int> Expr3 { get; set; }
        public string YevHesapKod { get; set; }
        public string BESHesapKod { get; set; }
        public Nullable<bool> IsGelirKaydindaKullanilacak { get; set; }
        public Nullable<decimal> SskPrimTutarTop { get; set; }
        public Nullable<decimal> TevkifatTutariTop { get; set; }
        public Nullable<decimal> TifTutarTop { get; set; }
    }
}
