//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class YevmiyelerYuzdeOnAsimHesapElleGirisler
    {
        public int YevmiyeYuzdeOnAsimHesapElleGirisID { get; set; }
        public System.DateTime Tarih { get; set; }
        public int YevmiyeHarcamaBirimID { get; set; }
        public string VergiKimlikNo { get; set; }
        public string HarcamaBirimAdi { get; set; }
        public int YevmiyeHesapKodHavuzID { get; set; }
        public string HesapKod { get; set; }
        public string HesapAdi { get; set; }
        public decimal BrutTutar { get; set; }
        public string Aciklama { get; set; }
        public bool IsAktif { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual YevmiyelerHarcamaBirimleri YevmiyelerHarcamaBirimleri { get; set; }
        public virtual YevmiyelerHesapKodHavuzu YevmiyelerHesapKodHavuzu { get; set; }
    }
}
