//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class YevmiyelerKdvTevkifatKayitlari
    {
        public int YevmiyeKdvTevkifatKayitID { get; set; }
        public int YevmiyeID { get; set; }
        public Nullable<int> YeniYevmiyeHesapKodID { get; set; }
        public string VergiKimlikNo { get; set; }
        public string AdSoyad { get; set; }
        public int FaturaYil { get; set; }
        public int FaturaAyID { get; set; }
        public decimal Matrah { get; set; }
        public int KdvOrani { get; set; }
        public decimal KdvTutari { get; set; }
        public int YevmiyeKdvKodID { get; set; }
        public string KdvKodu { get; set; }
        public string KdvKodOrani { get; set; }
        public int TevkifatOranBolunen { get; set; }
        public int TevkifatOranBolen { get; set; }
        public decimal TevkifatTutari { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual Aylar Aylar { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual YevmiyelerKdvKodlari YevmiyelerKdvKodlari { get; set; }
        public virtual YevmiyelerHesapKodlari YevmiyelerHesapKodlari { get; set; }
        public virtual Yevmiyeler Yevmiyeler { get; set; }
    }
}
