//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class YevmiyelerHesapKodlari
    {
        public int YevmiyeHesapKodID { get; set; }
        public int YevmiyeHesapKodTurID { get; set; }
        public string HesapKod { get; set; }
        public string HesapAdi { get; set; }
        public string VergiKodu { get; set; }
        public Nullable<int> TevkifatOranBolunen { get; set; }
        public Nullable<int> TevkifatOranBolen { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual YevmiyelerHesapKodTurleri YevmiyelerHesapKodTurleri { get; set; }
    }
}
