//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class YevmiyelerTasinirKontrolTifKaydi
    {
        public int YevmiyelerTasinirKontrolTifKayitID { get; set; }
        public int YevmiyeID { get; set; }
        public string TifNo { get; set; }
        public decimal Tutar { get; set; }
        public string Aciklama { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Yevmiyeler Yevmiyeler { get; set; }
    }
}
