//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class YevmiyelerBesBankaHesapNumaralari
    {
        public int YevmiyeBesBankaHesapNumaraID { get; set; }
        public bool IsYevmiyeDokumuAyriOlabilir { get; set; }
        public string HesapKod { get; set; }
        public string VergiKimlikNo { get; set; }
        public string FirmaAdi { get; set; }
        public string IBanNo { get; set; }
        public string Aciklama { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    }
}
