//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class YevmiyelerEslestirmeTurleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public YevmiyelerEslestirmeTurleri()
        {
            this.YevmiyelerEslestirmes = new HashSet<YevmiyelerEslestirme>();
        }
    
        public int YevmiyeEslestirmeTurID { get; set; }
        public string EslestirmeTurAdi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YevmiyelerEslestirme> YevmiyelerEslestirmes { get; set; }
    }
}
