//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class YevmiyelerHarcamaBirimleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public YevmiyelerHarcamaBirimleri()
        {
            this.KullaniciYevmiyeHarcamaBirimleris = new HashSet<KullaniciYevmiyeHarcamaBirimleri>();
            this.Yevmiyelers = new HashSet<Yevmiyeler>();
            this.Yevmiyeler1003BAyristirmalari = new HashSet<Yevmiyeler1003BAyristirmalari>();
            this.Yevmiyeler1003BSskPrimBoclari = new HashSet<Yevmiyeler1003BSskPrimBoclari>();
            this.YevmiyelerHarcamaBirimleriTutarKayits = new HashSet<YevmiyelerHarcamaBirimleriTutarKayit>();
            this.YevmiyelerYuzdeOnAsimHesapElleGirislers = new HashSet<YevmiyelerYuzdeOnAsimHesapElleGirisler>();
        }
    
        public int YevmiyeHarcamaBirimID { get; set; }
        public string VergiKimlikNo { get; set; }
        public string BirimAdi { get; set; }
        public bool IsUniversiteIsyeri { get; set; }
        public bool IsAltBirim { get; set; }
        public string SaymanlikKod { get; set; }
        public string IsyeriKodu { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciYevmiyeHarcamaBirimleri> KullaniciYevmiyeHarcamaBirimleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yevmiyeler> Yevmiyelers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yevmiyeler1003BAyristirmalari> Yevmiyeler1003BAyristirmalari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yevmiyeler1003BSskPrimBoclari> Yevmiyeler1003BSskPrimBoclari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YevmiyelerHarcamaBirimleriTutarKayit> YevmiyelerHarcamaBirimleriTutarKayits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YevmiyelerYuzdeOnAsimHesapElleGirisler> YevmiyelerYuzdeOnAsimHesapElleGirislers { get; set; }
    }
}
