//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yevmiyeler1003AGelirKayit
    {
        public int Yevmiye1003AGelirKayitID { get; set; }
        public int YevmiyeID { get; set; }
        public Nullable<int> YeniYevmiyeHesapKodID { get; set; }
        public string VergiKodu { get; set; }
        public Nullable<bool> IsHesaplamayaGirecek { get; set; }
        public string VergiKimlikNo { get; set; }
        public string AdSoyad { get; set; }
        public string Adres { get; set; }
        public Nullable<decimal> Matrah { get; set; }
        public string BelgeninMahiyeti { get; set; }
        public Nullable<System.DateTime> FaturaTarihi { get; set; }
        public string FaturaNo { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Yevmiyeler Yevmiyeler { get; set; }
        public virtual YevmiyelerHesapKodlari YevmiyelerHesapKodlari { get; set; }
    }
}
