//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class YevmiyelerHesapKodHavuzu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public YevmiyelerHesapKodHavuzu()
        {
            this.YevmiyelerYuzdeOnAsimHesapElleGirislers = new HashSet<YevmiyelerYuzdeOnAsimHesapElleGirisler>();
        }
    
        public int YevmiyeHesapKodHavuzID { get; set; }
        public string HesapKod { get; set; }
        public string HesapAdi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YevmiyelerYuzdeOnAsimHesapElleGirisler> YevmiyelerYuzdeOnAsimHesapElleGirislers { get; set; }
    }
}
