//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class YevmiyelerVergiKimlikNumaralari
    {
        public int YevmiyeVergiKimlikNoID { get; set; }
        public string VergiKimlikNo { get; set; }
        public string AdSoyad { get; set; }
        public string Adres { get; set; }
    }
}
