//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yevmiyeler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Yevmiyeler()
        {
            this.Yevmiyeler1003AGelirKayit = new HashSet<Yevmiyeler1003AGelirKayit>();
            this.Yevmiyeler1003BAyristirmalari = new HashSet<Yevmiyeler1003BAyristirmalari>();
            this.YevmiyelerKdvTevkifatKayitlaris = new HashSet<YevmiyelerKdvTevkifatKayitlari>();
            this.YevmiyelerTasinirKontrolTifKaydis = new HashSet<YevmiyelerTasinirKontrolTifKaydi>();
        }
    
        public int YevmiyeID { get; set; }
        public System.DateTime YevmiyeTarih { get; set; }
        public int YevmiyeNo { get; set; }
        public int YevmiyeHarcamaBirimID { get; set; }
        public string VergiKimlikNo { get; set; }
        public string HarcamaBirimKod { get; set; }
        public string HarcamaBirimAdi { get; set; }
        public string HesapKod { get; set; }
        public string HesapAdi { get; set; }
        public decimal Borc { get; set; }
        public decimal Alacak { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> Y1003AHesapKodID { get; set; }
        public string Y1003AVergiKodu { get; set; }
        public bool Y1003AIsHesaplamayaGirecek { get; set; }
        public string Y1003AVergiKimlikNo { get; set; }
        public string Y1003AAdSoyad { get; set; }
        public string Y1003AAdres { get; set; }
        public Nullable<decimal> Y1003AMatrah { get; set; }
        public Nullable<decimal> Y1003AKesintiTutar { get; set; }
        public string Y1003ABelgeninMahiyeti { get; set; }
        public Nullable<System.DateTime> Y1003AFaturaTarihi { get; set; }
        public string Y1003AFaturaNo { get; set; }
        public Nullable<int> EKYevmiyeHarcamaBirimID { get; set; }
        public Nullable<int> ProjeBankaHesapNoID { get; set; }
        public Nullable<int> YevmiyeSendikaBilgiID { get; set; }
        public Nullable<int> BESYevmiyeHesapKodID { get; set; }
        public string BESHesapKod { get; set; }
        public Nullable<bool> BESIsYevmiyeDokumuAyri { get; set; }
        public Nullable<bool> BESIsYevmiyeOdendi { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual YevmiyelerHarcamaBirimleri YevmiyelerHarcamaBirimleri { get; set; }
        public virtual YevmiyelerHesapKodlari YevmiyelerHesapKodlari { get; set; }
        public virtual YevmiyelerProjeBankaHesapNumaralari YevmiyelerProjeBankaHesapNumaralari { get; set; }
        public virtual YevmiyelerSendikaBilgileri YevmiyelerSendikaBilgileri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yevmiyeler1003AGelirKayit> Yevmiyeler1003AGelirKayit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yevmiyeler1003BAyristirmalari> Yevmiyeler1003BAyristirmalari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YevmiyelerKdvTevkifatKayitlari> YevmiyelerKdvTevkifatKayitlaris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YevmiyelerTasinirKontrolTifKaydi> YevmiyelerTasinirKontrolTifKaydis { get; set; }
    }
}
