//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yevmiyeler1003AMuhtasarKayitlari
    {
        public int Yevmiye1003AMuhtasarKayitID { get; set; }
        public int Yil { get; set; }
        public int AyID { get; set; }
        public string VergiKodu { get; set; }
        public decimal SksVergiTutar { get; set; }
        public decimal ImidVergiTutar { get; set; }
        public decimal GenelMatrahTutar { get; set; }
        public decimal SksMatrahTutar { get; set; }
        public decimal ImidMatrahTutar { get; set; }
    
        public virtual Aylar Aylar { get; set; }
    }
}
