//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yevmiyeler1003BAyristirmalari
    {
        public int Yevmiye1003BAyristirmaID { get; set; }
        public int YevmiyeID { get; set; }
        public int YevmiyeHarcamaBirimID { get; set; }
        public int Yil { get; set; }
        public int AyID { get; set; }
        public int YevmiyeBelgeKodID { get; set; }
        public decimal SskPrimTutar { get; set; }
        public decimal Matrah { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual Aylar Aylar { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Yevmiyeler Yevmiyeler { get; set; }
        public virtual YevmiyelerBelgeKodlari YevmiyelerBelgeKodlari { get; set; }
        public virtual YevmiyelerHarcamaBirimleri YevmiyelerHarcamaBirimleri { get; set; }
    }
}
