//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class YevmiyelerAyristirma
    {
        public int YevmiyelerAyristirmaID { get; set; }
        public int YevmiyeID { get; set; }
        public int BirimID { get; set; }
        public decimal Borc { get; set; }
        public decimal Alacak { get; set; }
        public string Aciklama { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual Birimler Birimler { get; set; }
        public virtual Yevmiyeler Yevmiyeler { get; set; }
    }
}
